language: node_js
node_js:
    - "6"
install:
    npm install

script:
  - git config user.name "ld000"
  - git config user.email "lidong9144@163.com"
  - hexo g
  - hexo d

branches:
  only:
    - dev
