language: node_js
node_js:
    - "6"
install:
    npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "ld000"
  - git config user.email "lidong9144@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - dev

env:
 global:
   - GH_REF: github.com/ld000/blog.git
